http:
  routers:
    grenobleski-http:
      rule: "Host(`grenobleski.fr`) || Host(`www.grenobleski.fr`)"
      middlewares:
        - grenobleski-https-redirect
      service: grenobleski-svc

    grenobleski-https:
      rule: "Host(`grenobleski.fr`) || Host(`www.grenobleski.fr`)"
      tls:
        certResolver: letsencrypt
      service: grenobleski-svc

  middlewares:
    grenobleski-https-redirect:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    grenobleski-svc:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:8081"
        passHostHeader: true
